### PR TITLE
Replace toml by tomli and tomli-w

### PR DESCRIPTION
**Pull request by bkmgit**

### CODE REVIEW

**Comment by glentner** [comment]
Outstanding. This is probably the right move going forward. Let me pull this down locally and play with it and we'll get it merged and released! ☕

**Comment by bkmgit** [comment]
Tests pass now, but not sure they are comprehensive. tomli and tomli-w use binary files, so
some conversion is needed to keep existing formats and interfaces.  If comments are needed
in the toml files [tomlkit](https://pypi.org/project/tomlkit/) provides more options.

**Comment by glentner** [comment]
Got the chance to play with this and will merge shortly.

The only alternative approach would be to have a singular hard dependency on `tomlkit` (for both read and write). I use `tomlkit` in other project to allow comment-preserving file updates but it's a heavier/harder dependency. Most users will be Python > 3.11 and not need write-capabilities so having no dependency is vastly preferable.

**Comment by glentner** [comment]
I'm going to add another commit to use package "extras" correctly. It would be better for users to `pip install cmdkit[toml]` and get both `tomli and tomli-w` in a single invocation.

**Comment by bkmgit** [comment]
Thanks.

**Comment by bkmgit** [comment]
Still need to check earliest versions of tomli and tomli-w that can be used.

**Comment by glentner** [comment]
For `tomli-w` the 1.0.0 tag is from 2021 and 1.1.0 is from this October. So I'm gonna stick with 1.1.0 for the requirements.

**Comment by glentner** [comment]
Similar story for `tomli`. Mostly devops stuff in past few months. Anything >2 is probably okay.

**Review by glentner — APPROVED** [review]
Everything looks good now.

**Comment by glentner** [comment]
This will be merged and closed and I'll release v2.7.6 shortly.

**Pull request merged**
