### PR TITLE
Capability to Override Version & Help 

### PR DESCRIPTION
**Pull request by alentner**
Provide the capability to override the default behavior of VersionOption and HelpOption.

This is needed in cases where the derived class desires to override (or monkey patch the base class) the default printing behavior of these try except cases.

This pull request also includes corrected type annotations for ApplicationGroup.commands.

### CODE REVIEW

**Comment by alentner** [comment]
Based on discussions, need to identify more correct name for the class methods "log_help" and "log_version"

**Comment by glentner** [comment]
I believe `handle_help` and `handle_version` would be appropriate.

**Review by glentner — CHANGES_REQUESTED** [review]
This looks fine. Wrapping this behavior in a function allows it to be modified more easily outside of `Application.main`. The method names need to be changed as we are not actually logging, but otherwise checks out.

**Review by glentner — APPROVED** [review]
Looks good.

**Pull request merged**
